# Generated by Django 5.1.4 on 2024-12-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('FIDE_rating', models.IntegerField(default=1000)),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
