# Generated by Django 5.1.4 on 2024-12-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birthdate',
        ),
    ]
